kubectl delete deployment ts-basic-service
kubectl delete deployment ts-config-service
kubectl delete deployment ts-contacts-service
kubectl delete deployment ts-order-service
kubectl delete deployment ts-notification-service
kubectl delete deployment ts-preserve-service
kubectl delete deployment ts-price-service
kubectl delete deployment ts-route-service
kubectl delete deployment ts-seat-service
kubectl delete deployment ts-station-service
kubectl delete deployment ts-ticketinfo-service
kubectl delete deployment ts-train-service
kubectl delete deployment ts-travel-service
kubectl delete deployment ts-user-service
kubectl delete deployment redis

kubectl delete service ts-basic-service
kubectl delete service ts-config-service
kubectl delete service ts-contacts-service
kubectl delete service ts-order-service
kubectl delete service ts-notification-service
kubectl delete service ts-preserve-service
kubectl delete service ts-price-service
kubectl delete service ts-route-service
kubectl delete service ts-seat-service
kubectl delete service ts-station-service
kubectl delete service ts-ticketinfo-service
kubectl delete service ts-train-service
kubectl delete service ts-travel-service
kubectl delete service ts-user-service
kubectl delete service redis