# apiVersion: v1
# kind: Service
# metadata:
#   name: rest-service-collect
#   labels:
#     app: rest-service-collect
# spec:
#   type: NodePort
#   ports:
#     - port: 9413
#   selector:
#     app: rest-service-collect
# ---

# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: rest-service-collect
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: rest-service-collect
#         version: v1
#     spec:
#       nodeName: k8snode3
#       containers:
#       - name: rest-service-collect
#         image: header/rest-service-collect
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 9413
#         volumeMounts:
#         - name: collect
#           mountPath: /parquet
#       volumes:
#       - name: collect
#         hostPath:
#           path: /home/parquet

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-basic-service
spec:
  selector:
    matchLabels:
      app: ts-basic-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-basic-service
    spec:
      containers:
      - name: ts-basic-service
        image: ts/ts-basic-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15680
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 15680
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-service
spec:
  selector:
    matchLabels:
      app: ts-config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-config-service
    spec:
      containers:
      - name: ts-config-service
        image: ts/ts-config-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15679
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 15679
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-contacts-service
spec:
  selector:
    matchLabels:
      app: ts-contacts-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-contacts-service
    spec:
      containers:
      - name: ts-contacts-service
        image: ts/ts-contacts-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12347
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12347
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-notification-service
spec:
  selector:
    matchLabels:
      app: ts-notification-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-notification-service
    spec:
      containers:
      - name: ts-notification-service
        image: ts/ts-notification-service
        imagePullPolicy: Always
        ports:
        - containerPort: 17853
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 17853
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-order-service
spec:
  selector:
    matchLabels:
      app: ts-order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-service
    spec:
      containers:
      - name: ts-order-service
        image: ts/ts-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12031
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12031
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-preserve-service
spec:
  selector:
    matchLabels:
      app: ts-preserve-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-preserve-service
    spec:
      containers:
      - name: ts-preserve-service
        image: ts/ts-preserve-service
        imagePullPolicy: Always
        ports:
        - containerPort: 14568
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 14568
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-price-service
spec:
  selector:
    matchLabels:
      app: ts-price-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-price-service
    spec:
      containers:
      - name: ts-price-service
        image: ts/ts-price-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16579
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 16579
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-route-service
spec:
  selector:
    matchLabels:
      app: ts-route-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-route-service
    spec:
      containers:
      - name: ts-route-service
        image: ts/ts-route-service
        imagePullPolicy: Always
        ports:
        - containerPort: 11178
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 11178
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-seat-service
spec:
  selector:
    matchLabels:
      app: ts-seat-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-seat-service
    spec:
      containers:
      - name: ts-seat-service
        image: ts/ts-seat-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18898
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 18898
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-user-service
spec:
  selector:
    matchLabels:
      app: ts-user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-user-service
    spec:
      containers:
      - name: ts-user-service
        image: ts/ts-user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12342
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12342
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-service
spec:
  selector:
    matchLabels:
      app: ts-station-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-service
    spec:
      containers:
      - name: ts-station-service
        image: ts/ts-station-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12345
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ticketinfo-service
spec:
  selector:
    matchLabels:
      app: ts-ticketinfo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ticketinfo-service
    spec:
      containers:
      - name: ts-ticketinfo-service
        image: ts/ts-ticketinfo-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15681
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 15681
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-train-service
spec:
  selector:
    matchLabels:
      app: ts-train-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-train-service
    spec:
      containers:
      - name: ts-train-service
        image: ts/ts-train-service
        imagePullPolicy: Always
        ports:
        - containerPort: 14567
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 14567
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-travel-service
spec:
  selector:
    matchLabels:
      app: ts-travel-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel-service
    spec:
      containers:
      - name: ts-travel-service
        image: ts/ts-travel-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12346
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12346
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  ports:
    - name: http
      port: 15680
  selector:
   app: ts-basic-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  ports:
    - name: http
      port: 15679
  selector:
   app: ts-config-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-service
spec:
  ports:
    - name: http
      port: 12347
  selector:
   app: ts-contacts-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-user-service
spec:
  ports:
    - name: http
      port: 12342
  selector:
   app: ts-user-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-notification-service
spec:
  ports:
    - name: http
      port: 17853
  selector:
   app: ts-notification-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  ports:
    - name: http
      port: 12031
  selector:
   app: ts-order-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
spec:
  ports:
    - name: http
      port: 14568
  selector:
   app: ts-preserve-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  ports:
    - name: http
      port: 16579
  selector:
   app: ts-price-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
spec:
  ports:
    - name: http
      port: 11178
  selector:
   app: ts-route-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-seat-service
spec:
  ports:
    - name: http
      port: 18898
  selector:
   app: ts-seat-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  ports:
    - name: http
      port: 12345
  selector:
   app: ts-station-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
spec:
  ports:
    - name: http
      port: 15681
  selector:
   app: ts-ticketinfo-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
spec:
  ports:
    - name: http
      port: 14567
  selector:
   app: ts-train-service


---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
spec:
  ports:
    - name: http
      port: 12346
  selector:
   app: ts-travel-service
