#spring:
#  data:
#    mongodb:
#      host: ts-preserve-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
server:
  port: 14568  # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-service
  rabbitmq:
    host: 101.132.193.242
    port: 5672
    password: guest
    username: guest
swagger:
  controllerPackage: preserve.controller

opentracing:
  jaeger:
    udp-sender:
      host: 101.132.193.242
      port: 6831