spring:
  application:
    name: ts-train-service
  data:
    mongodb:
      host: 101.132.193.242
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
  redis:
    host: 101.132.193.242
    port: 6379
# HTTP Server
server:
  port: 14567  # HTTP (Tomcat) port

swagger:
  controllerPackage: train.controller

opentracing:
  jaeger:
    udp-sender:
      host: 101.132.193.242
      port: 6831
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/