server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: 101.132.193.242
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller

opentracing:
  jaeger:
    udp-sender:
      host: 101.132.193.242
      port: 6831