spring:
  application:
    name: ts-route-service
  data:
    mongodb:
      host: 101.132.193.242
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 11178  # HTTP (Tomcat) port

swagger:
  controllerPackage: route.controller

opentracing:
  jaeger:
    udp-sender:
      host: 101.132.193.242
      port: 6831