server:
  port: 15680

spring:
  application:
    name: ts-basic-service
  redis:
    host: 101.132.193.242
    port: 6379
swagger:
  controllerPackage: fdse.microservice.controller

opentracing:
  jaeger:
    udp-sender:
      host: 101.132.193.242
      port: 6831